### ISSUE TITLE
patch gives "too much cpu" error on load, but then plays just fine right after. also patch sends loud noise on startup.

### ISSUE THREAD

**Issue by offthesky** [4ms/metamodule#365]
with system set to 48/512, load the patch. it will initially throw the "audio stopped due >99%" error. after pressing play on the patch a 2nd time, it starts playing ok.  otherwise load the patch a second time immediately after, it should load/work just fine.  it's never crashed after playing with it for several hours.  not sure if this cpu error on load is an actual bug (i don't notice this on the orca factory patch, that also runs at 80%ish). 

also i notice this patch sometimes sends a really loud noise burst through the reverb on load, so loud that the reverb takes over a minute to cool off/the sound to dissipate (granted the reverb is a long one!). is this a bug in one of the bog audio modules perhaps?

also when booting up the mm with this patch auto reloaded, often times it makes no sound at all (until i load one of the factory patches, then reload this one- at which point i often get the burst)

[EnterTheVoids.zip](https://github.com/user-attachments/files/16882528/EnterTheVoids.zip)

not sure what's going on with the sporadic behavior in the patch but im assuming maybe it's to do with the bog or fundamental modules im leaning heavily on.

**Comment by offthesky** [comment]
i think i may have pinpointed the load spikes to patches that use a feedback array with bog cvd delays. i have another patch that is basically just cvds and vcv mix modules - multiple loopers. it clocks in max 60%, yet exhibits the same patch load spike behavior. and it also seems overloads when i turn a meta knob that is mapped to the delay time on all the cvds.  when i have time i'll do more tests to try and better verify this issue with another patch example posted here.

**Comment by danngreen** [comment]
Ok, yeah I'm looking at the CVD code and it does some dynamic allocation in the "hot" loop the first time it gets called. It sets up the delay engine, which spikes the CPU. I think some other Bogaudio modules do this too?

So this probably should be addressed in the Bogaudio code...

But -- I did just make a workaround on the MetaModule which just runs each module once when you load the patch. We'll need to test this a bit more, it could have unintended consequences. But it does work for this patch (starts right away, no huge noise).
Here's that version: https://github.com/4ms/metamodule/releases/download/firmware-v1.1.1-fix1/metamodule-firmware-v1.1.1-fix1-firmware-assets.zip

Nice patch, too BTW!

**Comment by offthesky** [comment]
thanks! really appreciate all your help with this one(and all the other issues)!!! finger's crossed i can perform with these patches ok at an upcoming event early oct.  so i've tried out this new 1.1.1 fix 1 and im still get those loud pops at the intro at times, and also random spikes/audio shutoff now while playing enterthevoids one, it seems to happen when i turn different knobs (for example the feedback input, which is just the vcv mix module)

attached is another tester that also runs a lot of cvd's and vcv mixes, with that air windows verb. this clocks around a moderate 67%, yet i still get random spikes/audio shutoff while turning knobs related to the vcv mix module.

[DualLooperFX+Vrb.zip](https://github.com/user-attachments/files/16901461/DualLooperFX%2BVrb.zip) - in at just under 32 modules ;]

**Comment by danngreen** [comment]
Ok, wow I suppose I should raise the module limit to 64. I didn't think any interesting patch with 32 modules would run. But I guess I was wrong!

Regarding this patch and clicks, I think this is due to the modules themselves because I get far fewer issues with block size at max. There's nothing the MetaModule can do about a module's code taking too long to do its processing. On a host computer this often evens out or is just a click, but the MetaModule has hard real-time requirements, which it needs to in order to guarantee a particular latency. We'd need to modify the plugin's code to have it do intensive tasks up front (like allocating delay lines), instead of during audio processing.

Re: long delays.. have you tried the DLD? It has two channels with up to 3 minutes each.

**Comment by offthesky** [comment]
you won't find me complaining about a higher module limit in mm, although if we eventually see something like stackable inputs, (or maybe that prototype module within mm), will probably never come close to the limit then

also thank you for that tip- i didn't realize that about the DLD, very nice! time to dig into some manuals (for all the 4ms ones really) and reconfig this looper patch

re patch/clicks/improving plugins- down to test out whenever wherever needed there!

**Comment by danngreen** [comment]
Cool, I'm going to close this here since there's nothing to be done in the firmware about this. If we can narrow down which module or set of modules cause issues, then we can open up an issue in the [metamodule-plugin-examples](https://github.com/4ms/metamodule-plugin-examples/issues) repo (or report in the forum, that's fine too). Just trying to stay organized!
